# Generated by Django 3.2.12 on 2024-03-28 09:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfrustructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='InfrustructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('infrustructure_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='small_farms_app.infrustructureitem')),
                ('infrustructure_log_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='small_farms_app.logaction')),
            ],
        ),
        migrations.AddField(
            model_name='infrustructureitem',
            name='infrustructure_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='small_farms_app.infrustructuretype'),
        ),
    ]
