# Generated by Django 5.0.3 on 2024-04-30 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0002_mostpopulationrecorduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MostPopulationRecordUser',
        ),
    ]
